from .KNN.knn import knn
from .KMEANS.kmeans import kmeans
from .DMC.dmc import dmc
from .PERCEPTRON.perceptron import perceptron
from .ADALINE.adaline import adaline
from .SIMPLE_PERCEPTRON_NET.generic_neuron import generic_neuron
from .SIMPLE_PERCEPTRON_NET.simple_perceptron_net import simple_perceptron_network
from .SIMPLE_PERCEPTRON_NET.sigmoid_perceptron_net import sigmoid_perceptron_network
from .SIMPLE_PERCEPTRON_NET.hyperbolic_perceptron_net import hyperbolic_perceptron_network
from .MULTILAYER_PERCEPTRON_NET.mlp import MultiLayerPerceptron
from .RADIUS_BASES_FUNCTION_NET.RBF import RadialBasisFunction
from .EXTREME_LEARNING_MACHINE.ELM import ExtremeLearningMachines
from .BAYESIAN.gaussian_bayes import gaussianBayes
from .LINEAR_DISCRIMINANT.linear_discriminant import linearDiscriminant
from .QUADRATIC_DISCRIMINANT.quadratic_discriminant import quadraticDiscriminant
